# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms
name: Topic Request
description: Request a topic for me to explore!

title: "TOPIC REQUEST: topic_name"
labels: ["topic-request"]
assignees: ["N1femi"]

body: 
  - type: dropdown
    attributes:
      label: Relevance
      description: What category is your request most closely associated with?
      options:
        - Data Structures/Algorithms 📔
        - Software Development 👨🏾‍💻
        - AI/ML 🤖
    validations:
      required: true

  - type: textarea
    attributes:
      label: Extra Notes
      description: Anything you need to say?
      placeholder: Blah Blah Blah
    validations:
      required: false
        
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute!
        > You can ignore everything below this and just Submit!

    
    


  
