# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms
name: Topic Request
description: Request a topic for me to explore!

title: "TOPIC REQUEST: "
labels: ["topic-request"]

body: 
  - type: dropdown
    attributes:
      options:
        - Data Structures/Algorithms 📔
        - Software Development 👨🏾‍💻
        - AI/ML 🤖
      label: Relevance
      description: What category is your request most closely associated with?
    validations:
      required: true

    
    


  
