# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms
name: Test Template
description: A testy template to test a template intended for testing a template test

title: "TOPIC REQUEST: "
labels: ["topic-request"]

body: 
  - type: dropdown
    attributes:
      options:
        - Data Structures/Algorithms 📔
        - Software Development 👨🏾‍💻
        - AI/ML 🤖
      multiple: true
      label: Relevance
      description: What category is your request most closely associated with?

    
    


  
